name: Add New Event
description: Use this issue to automatically create a pull request to add a new event to the website with all of the required information
labels: New Event
body:
  - type: markdown
    attributes:
      value: |
       Please carefully follow all of the instructions to create a pull request to add a new Data Saturday event to the web-site

  - type: input
    id: name
    attributes:
      label: eventname
      description: "What is the name of the event - This is normally the name of the city/country or region. For example Slovenia, Cambridge, Dallas, Rheinland"
      placeholder: Slovenia"
      value: Replace me with the name of your event
    validations:
      required: true  
  - type: input
    id: date
    attributes:
      label: date
      description: |
       The date of your event in YYYY-MM-DD HH:mm:ss TZ For example 2022-06-30 08:00:00 -00:00 
       https://www.digi.com/resources/documentation/digidocs/90001437-13/reference/r_iso_8601_date_format.htm"
      placeholder: "2022-06-30 08:00:00 -00:00"
      value: 2022-06-30 08:00:00 -00:00
    validations:
      required: true
  - type: textare
    id: description
    attributes:
      label: description
      description: |
       Place the description of your event here, you may use HTML. You may NOT use scripts

       If you wish to add images - external images can be referenced using HTML for example <img src="imagelink" width="225" height="225">
      render: html
    validations:
      required: true
