name: Add New Event
description: Use this issue to automatically create a pull request to add a new event to the website with all of the required information
labels: ["New Event"]
body:
  - type: markdown
    attributes:
      value: |
       Please carefully follow all of the instructions to create a pull request to add a new Data Saturday event to the web-site
  - type: input
    id: name
    attributes:
      label: eventname
      description: "What is the name of the event - This is normally the name of the city/country or region. For example Slovenia, Cambridge, Dallas, Rheinland"
      placeholder: Slovenia"
      value: Replace me with the name of your event
    validations:
      required: true  
  - type: input
    id: date
    attributes:
      label: date
      description: |
       The date of your event in YYYY-MM-DD HH:mm:ss TZ For example 2022-06-30 08:00:00 -00:00 
       https://www.digi.com/resources/documentation/digidocs/90001437-13/reference/r_iso_8601_date_format.htm
      placeholder: "2022-06-30 08:00:00 -00:00"
      value: "2022-06-30 08:00:00 -00:00"
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: description
      description: |
       Place the description of your event here, you may use HTML. You may NOT use scripts
    validations:
      required: true
  - type: input
    id: registrationurl
    attributes:
      label: registrationurl
      description: |
        This is your attendee registration URL. You can leave this blank at first and update it later if need be.
  - type: textarea
    id: rooms
    attributes:
      label: rooms
      description: |
        If you are a virtual event with multiple tracks, you can add the name and the entry URL to those rooms. Make sure that it follows the template below.
        roomname1:roomurl1,roomname2:roomurl2,roomname3:roomurl3
      placeholder: "roomname1:roomurl1,roomname2:roomurl2,roomname3:roomurl3"
      value: roomname1:roomurl1,roomname2:roomurl2,roomname3:roomurl3
  - type: input
    id: scheduleurl
    attributes:
      label: scheduleurl
      description: |
         This is your schedule API URL from Sessionize. You can leave this blank until you have it.
      placeholder: https://sessionize.com/api/v2/APITAG/view/GridSmart
      value: https://sessionize.com/api/v2/APITAG/view/GridSmart
  - type: textarea
    id: sponsors 
    attributes:
      label: sponsors 
      description: |
        You can add as many sponsors as you wish or none at all. If there are no sponsors, your site will display a message suggesting that if anyone wishes to sponsor the event to contact you and a link to the contact (see below) Make sure that it follows the template below.
        The height is the height of the sponsor image. The link is the URL of the sponsor. The name is the name of the sponsor. 
        sponsor1link:sponsor1name:sponsor1height,sponsor2link:sponsor2name:sponsor2height,sponsor3link:sponsor3name:sponsor3height
      placeholder: "sponsor1link:sponsor1name:sponsor1height,sponsor2link:sponsor2name:sponsor2height,sponsor3link:sponsor3name:sponsor3height"
      value: sponsor1link:sponsor1name:sponsor1height,sponsor2link:sponsor2name:sponsor2height,sponsor3link:sponsor3name:sponsor3height
  - type: input
    id: speakerlisturl
    attributes:
      label: speakerlisturl
      description: |
        The URL to your Sessionize Call for speakers page.
      placeholder: "https://sessionize.com/data-saturday-parma-2022/"
      value: https://sessionize.com/data-saturday-parma-2022/
  - type: input
    id: volunteerrequesturl
    attributes:
      label: volunteerrequesturl
      description: |
        If you want a link for people to volunteer place it here - maybe its a webform, maybe its an email address.
  - type: textarea
    id: organizers  
    attributes:
      label: organizers  
      description: |
        Add the details of the organizers and their contact details here. You can add as many as you wish. make sure to use the full twitter URL or other social media URL.

        organizer1name:organizer1twitter:organizer1email,organizer2name:organizer2twitter:organizer2email,organizer3name:organizer3twitter:organizer3email
      placeholder: "organizer1name:organizer1twitter:organizer1email,organizer2name:organizer2twitter:organizer2email,organizer3name:organizer3twitter:organizer3email"
      value: organizer1name:organizer1twitter:organizer1email,organizer2name:organizer2twitter:organizer2email,organizer3name:organizer3twitter:organizer3email
