name: Create a New Event PR

on: 
 issues:
   types:
     - "opened"

jobs:
  process:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get Information to file
      run: |
        Write-Host "What do we have?"
        $IssueBody =  @"
        ${{ github.event.issue.body }}
        "@
        # Write-Host $IssueBody 
        $IssueBody | Out-File ./temp/temp.txt
      shell: pwsh   
    - name: Add & Commit
      uses: EndBug/add-and-commit@v8.0.2
      with:
        author_name: Beardy McBeardFace
        author_email: mrrobsewell@outlook.com
        message: 'Added the temp file to the repo for ${{ github.event.issue.number }} raised by  @${{ github.event.issue.user.login }}'
    - name: Parse the temp file and create the others
      run: |
        # get the temp file contents - I do this so I dont lose anything
        $file = Get-Content ./temp/temp.txt -Raw
        # parse the issue
        $regexResult = [regex]::Matches($file, '(?ms)eventname\n\n(?<eventname>.*)\n\n### date\n\n(?<date>.*)\n\n### description\n\n(?<description>.*)\n\n### registrationurl\n\n(?<registrationurl>.*)\n\n### rooms\n\n(?<rooms>.*)\n\n### scheduleurl\n\n(?<scheduleurl>.*)\n\n### sponsors\n\n(?<sponsors>.*)\n\n### speakerlisturl\n\n(?<speakerlisturl>.*)\n\n### volunteerrequesturl\n\n(?<volunteerrequesturl>.*)\n\n### organizers\n\n(?<organizers>.*)\n')
        # create an object
        $eventObject = [PSCustomObject]@{
            eventname =  $regexResult[0].Groups['eventname'].Value
            date = $regexResult[0].Groups['date'].Value
            description = $regexResult[0].Groups['description'].Value
            registrationurl = $regexResult[0].Groups['registrationurl'].Value
            rooms = $regexResult[0].Groups['rooms'].Value
            scheduleurl = $regexResult[0].Groups['scheduleurl'].Value
            sponsors = $regexResult[0].Groups['sponsors'].Value
            speakerlisturl = $regexResult[0].Groups['speakerlisturl'].Value
            volunteerrequesturl = $regexResult[0].Groups['volunteerrequesturl'].Value
            organizers = $regexResult[0].Groups['organizers'].Value
        }
        #save it to a file
        $eventname = $eventObject.eventname -replace ' ', '-' -replace '''','-' -replace '/','-' -replace '\\','-' -replace ':','-' -replace '\*','-' -replace '\?','-' -replace '"','-' -replace '\|','-'
        $filePath = './temp/{0}.json' -f $speakerFileName
        $eventObject |ConvertTo-Json | Out-FIle -FilePath $filePath
        $speakerFileName | OUt-File ./speakers/list.txt -Append
      shell: pwsh   
    - name: Add & Commit
      uses: EndBug/add-and-commit@v8.0.2
      with:
        author_name: Beardy McBeardFace
        author_email: mrrobsewell@outlook.com
        message: 'Added the parsed event file to the repo for ${{ github.event.issue.number }} raised by  @${{ github.event.issue.user.login }}'
    - name: Close Issue
      uses: peter-evans/close-issue@v2
      with:
        issue-number: ${{ github.event.issue.number }}
        comment: |
          Hey @${{ github.event.issue.user.login }},
          Closing this issue now whilst we dev