name: Create a New Event PR

on: 
 issues:
   types:
     - "opened"

jobs:
  createNewEventPr:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with: 
       clean: true
       fetch-depth: 0
    - name: Get Information to file
      run: |
        Write-Host "What do we have?"
        $IssueBody =  @"
        ${{ github.event.issue.body }}
        "@
        # Write-Host $IssueBody 
        $IssueBody | Out-File ./temp/temp.txt
      shell: pwsh
      continue-on-error: true   
    - name: Add & Commit
      uses: EndBug/add-and-commit@v8.0.2
      with:
        author_name: Beardy McBeardFace
        author_email: mrrobsewell@outlook.com
        message: 'Added the temp file to the repo for issue number #${{ github.event.issue.number }} raised by @${{ github.event.issue.user.login }} ***NO_CI***'
        new_branch:  'new-event-issue-${{ github.event.issue.number }}'
        push: origin new-event-issue-${{ github.event.issue.number }} --set-upstream --force
      continue-on-error: true
    - name: pull-request
      uses: repo-sync/pull-request@v2
      with:
        source_branch: 'new-event-issue-${{ github.event.issue.number }}'                                 # If blank, default: triggered branch
        destination_branch: "main"                      # If blank, default: master
        pr_title: "Pulling ${{ github.ref }} into master" # Title of pull request
        pr_body: ":crown: *An automated PR*"              # Full markdown support, requires pr_title to be set
        pr_reviewer: "SQLDBAWithABeard"                         # Comma-separated list (no spaces)
        pr_assignee: "SQLDBAWithABeard"                         # Comma-separated list (no spaces)
        pr_label: "new-event"                               # Comma-separated list (no spaces)                    # Milestone name

        github_token: ${{ secrets.GITHUB_TOKEN }}

