name: Create a New Event PR

on: 
 issues:
   types:
     - "opened"

jobs:
  process:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get Information to file
      run: |
        Write-Host "What do we have?"
        $IssueBody =  @"
        ${{ github.event.issue.body }}
        "@
        Write-Host $IssueBody 
        $IssueBody | Out-File /temp/test.txt
      shell: pwsh   

    - name: Add & Commit
      uses: EndBug/add-and-commit@v8.0.2
      with:
        author_name: Beardy McBeardFace
        author_email: mrrobsewell@outlook.com
        message: 'Hi, Thank you for your contribution to the Data Saturday event repo'