name: Create a New Event PR

on: 
 workflow_dispatch

jobs:
  createNewEventPr:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with: 
       clean: true
       fetch-depth: 0
    - name: Get Information to file
      run: |
        Write-Host "What do we have?"
        $IssueBody =  @"
        Just some junk
        "@
        # Write-Host $IssueBody 
        $IssueBody | Out-File ./temp/temp.txt -Force
      shell: pwsh
      continue-on-error: true   
    - name: Add & Commit
      uses: EndBug/add-and-commit@v8.0.2
      with:
        author_name: Beardy McBeardFace
        author_email: mrrobsewell@outlook.com
        message: 'Added the temp file to the repo for issue number #${{ github.event.issue.number }} raised by @${{ github.event.issue.user.login }} ***NO_CI***'
        new_branch:  'new-event-issue-${{ github.event.issue.number }}'
        push: origin new-event-issue-${{ github.event.issue.number }} --set-upstream --force
      continue-on-error: true

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
       assignees: SQLDBAWithABeard #,SpaghettiDba
       reviewers: SQLDBAWithABeard #,SpaghettiDba
       labels: "New Event"
       base: main
       branch:  'new-event-issue-${{ github.event.issue.number }}'
       body: |
        Pull Request created for new event for issue number #${{ github.event.issue.number }} raised by  @${{ github.event.issue.user.login }}

