name: Create a New Event PR

on: 
 workflow_dispatch

jobs:
  createNewEventPr:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with: 
       clean: true
       fetch-depth: 0
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
       assignees: SQLDBAWithABeard #,SpaghettiDba
       reviewers: SQLDBAWithABeard #,SpaghettiDba
       labels: "New Event"
       base: main
       branch:  'newbranch'
       body: |
        Pull Request created for new event for issue number #${{ github.event.issue.number }} raised by  @${{ github.event.issue.user.login }}

